### ISSUE TITLE
Please do not change Bullet Behavior default

### ISSUE THREAD

**Issue by RalfJung** [math-comp/math-comp#102]
I find it slightly irritating that importing ssreflect will change Coq's Bullet Behavior option to "None" (where the default is "Strict Subproofs"). Obviously I do not care which options are used inside the implementation of ssreflect, but I would prefer if the library would not impose its choice onto the user, forcing them to explicitly revert the option back to the default. Worse, what will probably actually happen is that many ssreflect users don't even know that Coq can enforce bullets, because they never see a "vanilla" Coq.

Is there a deep reason why importing ssreflect changes the bullet option of its reverse dependencies? If not, I think it's a matter of politeness not to unnecessarily change global configuration options as a library.

**Comment by ejgallego** [comment]
Just a small comment @RalfJung , if my understanding is correct ssreflect's bullet implementation predates the Coq's one, thus ssreflect is not "imposing" anything, it was Coq who chose a different behavior AFAIK.

**Comment by gares** [comment]
Unfortunately mathcomp cannot compile with the "strict subproof" option set.  As @emilio says,  we had tons of Coq files using bullets when 8.4 came out.

I could have set the behavior to None in each an every file. I went the lazy way of setting it globally.

I guess your request makes sense, but adding extra line in the heder of each and every file is not very nice.
Are there better options?

**Comment by maximedenes** [comment]
As a side note, I believe compatibility was not the only reason not to adopt the new behavior. It was not clear if bullets were the right construct for focusing, and they were made strict in a way that is not always helpful for maintenance.

**Comment by ejgallego** [comment]
Of course it is just a very personal opinion, but I agree with Maxime. I don't like the strict mode, I guess I never got used to that style.

**Comment by RalfJung** [comment]
That's fine of course if you don't like the strict mode, but I find it a little obtrusive then to disable default mode for everyone using your library.

> I guess your request makes sense, but adding extra line in the heder of each and every file is not very nice.
> Are there better options?

I am currently trying to figure out exactly that for Iris (also see my questions and coq-club).

**Comment by ejgallego** [comment]
> importing ssreflect will change the global Coq configuration, and that's not usually something you would expect a library to do, I feel

I feel that ssreflect is way beyond what we understand as a "library": it basically redefines the whole tactic language and changes many things in gallina too. I would expect such plugins in the future to modify unification, TC inference, and many other things.

**Comment by gares** [comment]
FTR: the main issue we have with the strict focusing is that it imposes a bullet for the last case, and this would force us to indent at an insane level.  In ssr scripts are like:
```
case: ...
- first trivial goal
next relevant goal goal
case: ...
- trivial side condition
we go on here
```
where the main argument is not indented (and we also omit - if there is just one silly subgoal).
If we go in strict mode we get
```
case: ...
- first trivial goal
- next relevant goal goal
  case: ...
  - trivial side condition
  - we go on here
```
In some sense, each time you have a few silly side conditions you loose 2 columns.  For proofs 300 lines long, this is not an option.

Last, - is a decorator used for other purposes too.  E.g.
```
have H : long long
  long statement.
- beginning of sub proof, easy to find thanks to the -
  more on this
  by something, end of proof easy to spot because "by" is colored in red
back to the main proof branch using H
```

Not sure who selected the default behavior of - in Coq did check on math-comp :-/

**Comment by RalfJung** [comment]
It seems we have a clash of different conventions here -- admittedly, I only really started to do serious Coq when proof bullets were already a thing in Coq, but I am extremely happy about the enforcing mode. It has time and time again been very helpful in fixing broken proofs, because it makes it immediately clear which tactic was supposed to work on which goal -- and it actually tests that this is really the case, i.e., you can rely on it.

For the "bullet for the last case", we will typically write
```
case:...
{ trivial sidecondition }
work. on. main. goal.
apply: lemma_with_two_easy_sideconditions_and_a_main_remaining_goal.
{ first trivial goal. }
{ second trivial goal. }
main. proof. goes. on.
```

> I feel that ssreflect is way beyond what we understand as a "library": it basically redefines the whole tactic language and changes many things in gallina too. I would expect such plugins in the future to modify unification, TC inference, and many other things.

I can see this point. On the other hand, I am not sure this is very desirable -- what if you want to use two libraries that both claim to be "way more than just a library"?
As far as we are concerned, ssreflect is a library that brings us a way better rewrite tactic, some nice tacticals for introduction (`=>...`), as well as `last` and `first`. We overwrite `done` with our own tactic. We occasionally use `apply:` and `exact:`, but often we actually need `eapply`. Maybe we're not using it "as intended" then, which may give us a different perspective, but we're still very happy users :)

**Comment by RalfJung** [comment]
I should also add that we have a fairly easy work-around for this issue in our development; we just set Bullet Behavior back to its default. If you feel the proof style is really something that the vast majority of your users should use, and our use case is too niche, I won't be bad if you just close this. I was curious why ssreflect does what it does here, and honestly I had forgotten for a minute that we are maybe rather uncommon in the way we use ssreflect ;)

**Comment by ejgallego** [comment]
Just a quick note, AFAIU the "see which tactic works for which goal" is more or less enforced in the MC library by requiring every proof to end with `by`. This seems to work as well as strict bullets AFAIC.

**Comment by herbelin** [comment]
Hi, I've been directed to this discussion by @ejgallego at https://github.com/coq/ceps/pull/16. If ssreflect would be interested in taking benefit of the semantical aspects of bullets without breaking the mathcomp library, it is certainly possible to design a variant of the strict mode which makes optional the last bullet of a block of goal, and which gives a different meaning to `-`, compatible with its use in mathcomp.

Alternatively, at some time in the future, it is not impossible that a tool to apply transformations to proof script is made available. Then, if ever mathcomp is interested, such a script could probably turn cases of the form indicated by @gares into bracketed items, or into, say, scripts using a dedicated bullet, say `side:`, or whatever other form of wishes the mathcomp library designers would like to implement.

**Comment by Zimmi48** [comment]
> it is certainly possible to design a variant of the strict mode which makes optional the last bullet of a block of goal, and which gives a different meaning to `-`, compatible with its use in mathcomp

Are you sure it is "certainly possible"? We could imagine solutions to do that, I guess, but I think that there is a fundamental reason why the semantic bullets which were introduced in Coq were made incompatible with the ones of SSReflect (as Emilio was complaining about). This is because SSReflect's bullets are relying on indentation to separate blocks. I would argue that we don't want to give a semantics to indentation in Coq, thus we need to have a way to mark the beginning and the end of a focusing block. This is done with either opening and closing brackets (in Lean I believe they only have brackets), or with bullets (then the next bullet marks the end of the previous one). Brackets are more flexible and are compatible with mathcomp's style, with a main goal back at the indentation level of the previous one. This answers by the way Enrico's concern:

> FTR: the main issue we have with the strict focusing is that it imposes a bullet for the last case, and this would force us to indent at an insane level.

----

> at some time in the future, it is not impossible that a tool to apply transformations to proof script is made available

Yes, I am the one developing such a tool. I talked about it over lunch with Enrico, among others. If the mathcomp maintainers were to agree to adapt their style to replace the current use of bullets with brackets, I could make efforts to make sure that the needed refactoring can indeed be conducted automatically.

> or into, say, scripts using a dedicated bullet, say `side:`

You are using here for an hypothetical bullet a syntax that has been used up-to-know for goal selectors. I don't think that it is a good idea to reinforce the confusion between the two.

> It was not clear if bullets were the right construct for focusing

From this remark and some others from Maxime, it left me wondering if there is a real problem with bullets as they are currently or if it's just a problem of people who are used to a different style. There is maybe an interesting discussion to be had. At the very least, there is this problem of unfocused sub-goals not being printed.

**Comment by Zimmi48** [comment]
I guess that this issue could be closed now because when using SSReflect in Coq 8.7 with the command:

    From Coq Require Import ssreflect.

the behavior of bullets is not changed, as requested here.
On the contrary (if I'm not mistaken), `From mathcomp Require Import ssreflect.` will continue to work and will still change the bullet behavior.

**Comment by Zimmi48** [comment]
@gares ping, you probably want to close this.
