### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/math-comp#1277]
https://github.com/math-comp/math-comp/blob/1a734557e6feba27221a8b9bc5fff8ebf6da537a/mathcomp/algebra/ssralg.v#L108

should be `@LRMorphism.type R A B`
or better the notation `lrmorphism` should be documented instead

@hivert @Tragicus

**Comment by hivert** [comment]
It is not clear in the documentation (and actually for me) why they are two different notation:
` Additive.type U V` and `{additive U -> V}` and the like... Moreover `grep Additive.type **/*.v` only shows:
```
algebra/rat.v:pose phi : GRing.Additive.type U V := HB.pack f aM.
algebra/ssralg.v:(*     Additive.type U V == semi additive (resp. additive) functions between  *)
algebra/ssralg.v:Notation "{ 'additive' U -> V }" := (Additive.type U%type V%type) : type_scope.
```
For ring morphisms `grep RMorphism.type **/*.v` shows
```
algebra/mxpoly.v:pose phiRM : GRing.RMorphism.type _ _ := HB.pack phi phiaM phimM.
algebra/ssralg.v:(*    RMorphism.type R S == semi ring (resp. ring) morphism between           *)
algebra/ssralg.v:(* LRMorphism.type R A B == linear ring morphisms, i.e., algebra morphisms    *)
algebra/ssralg.v:Notation "{ 'rmorphism' U -> V }" := (RMorphism.type U%type V%type)
algebra/ssralg.v:Notation "{ 'lrmorphism' A -> B | s }" := (@LRMorphism.type _ A%type B%type s)
field/algebraics_fundamentals.v:    pose fRM : GRing.RMorphism.type _ _ := HB.pack f faM fmM.
field/algebraics_fundamentals.v:pose conjRM : GRing.RMorphism.type _ _ := HB.pack conj conjaM conjmM.
field/algnum.v:pose nu0RM : GRing.RMorphism.type _ _ := HB.pack nu0 nu0aM nu0mM.
field/algnum.v:pose phiRM : GRing.RMorphism.type _ _ := HB.pack (fun_of_lfun phi) phimM.
field/closed_field.v:pose EtoKM i : GRing.RMorphism.type _ _ :=
field/galois.v:pose fRM : GRing.RMorphism.type _ _ := HB.pack (fun_of_lfun f) fmM.
field/galois.v:pose fjRM : GRing.RMorphism.type _ _ := HB.pack (fun_of_lfun fj) fjmM.
```
I'm not sure what is the proper course of action. I see a few possibilities
1 - Remove the `GRing.Kind.type` notation from the documentation. 
2 - Deprecate and later remove the `{morphism U -> V}` notations.
3 - Document both as aliases, stating which one should be used preferably.

My opinion : I prefer solution 3
PRO for keeping one of the notation:
-  `GRing.Kind.type` should be kept somewhere as it is consistent with `HB.Kind.Build`, `HB.Kink.Clone`,
-  I'm used to `{morphism U -> V}` and I find it more readable as it stress the fact that those are glorified functions.

CONS:
- Two notations for the same thing is confusing.
- My understanding is that `{additive U -> V}`  notation was used to trigger some `Canonical` magic through phantoms to make sure that `U` and `V` are actually `Zmodule`s, but this is not needed anymore (perhaps because of reverse coercion). I might be totally wrong about this whole point. Please correct me.
- `{additive U -> V}`  need to be declared by hands while `GRing.Kind.type` is automatically defined by `HB`.

Please comment further !

**Comment by proux01** [comment]
Yes, you're right, `Additive.type` is the thing unavoidably given by HB but `{additive _ -> _}` is the preferred notation. It's quite possible that a number of instances of the former can be replaced by the latter, both in code and doc. PR welcome I guess if you want to improve that.

**Comment by hivert** [comment]
> It's quite possible that a number of instances of the former can be replaced by the latter, both in code and doc. PR welcome I guess if you want to improve that.

I checked yesterday a few appearance detected by my grep above, and they can be replaced. I'm putting up a PR.
