### ISSUE TITLE
Coercion rat >-> int

### ISSUE THREAD

**Issue by hivert** [math-comp/math-comp#227]
Is there a good reason why there is no coercion int >-> rat in mathcomp ?
Looking at the file rat.v one can see that is has been considered but commented out:
```
  Definition ratz (n : int) := @Rat (n, 1) (coprimen1 _).
  (* Coercion ratz (n : int) := @Rat (n, 1) (coprimen1 _). *)
```
One possible reason is given later:
```
  (* ratz should not be used, %:Q should be used instead *)
  Lemma ratzE n : ratz n = n%:Q.
```

I moreover noticed that the doc is wrong saying:
```
(*         n%:Q == explicit cast from int to rat, postfix notation for the    *)
(*                 ratz constant                                              *)
```
Indeed, it is acually the following notation
```
Notation "n %:Q" := ((n : int)%:~R : rat)
  (at level 2, left associativity, format "n %:Q")  : ring_scope.
```
which ultimately is `intmul 1 n` which is denoted `intr`.

To sumarize, my question becomes: Is the a good reason not to write something as
```
Definition int_to_rat : int -> rat := intr.
Coercion int_to_rat : int >-> rat.
```
and fixing the wrong doc ?

If its Ok, I'll summit a PR.

**Comment by CohenCyril** [comment]
@hivert The doc is indeed wrong and the coercion is dangerous... I'll explain later or ping me if I forget.

**Comment by hivert** [comment]
OK ! I'm just submitting a PR fixing the doc.

**Comment by amahboubi** [comment]
ping @CohenCyril : you did not explain.

**Comment by CohenCyril** [comment]
@hivert the problem with such a coercion is that a ring expression such as `x + y` (where `x` and `y` have type `int`) is too ambiguous for the human user/reader (indeed, in such an expression, the coercions could have been inserted in many ways, here `intr (x + y)` or `intr x + intr y`). This is already problematic for the `nat` to `int` coercion, but at least, since `nat` does not have any algebraic structure in mathcomp, the operators are different.
The best practice to avoid coercions (explicit or implicit) everywhere, is to work as much as possible in the biggest type at hand (e.g. `rat` or even `algC`) and use predicates to characterize subring elements.

**Comment by amahboubi** [comment]
HI @CohenCyril. I agree with the best practice you suggest, but there is (at least) one situation in which I found it painful to put into practice: in the case of sequences with a closed form or a recurrence/functional equation defined in terms of the indices. Like e.g. `u_(n + 1) = n*(n + 1)* u_n`, with `n` implicitly universally quantified here. Note that I find the `Posz` coercion even more problematic than the one suggested by @hivert, because there is much less convertible terms that look alike.

**Comment by hivert** [comment]
I'm closing the issue since #228 is merged
