### ISSUE TITLE
Add more libraries to Continuous Integration?

### ISSUE THREAD

**Issue by anton-trunov** [math-comp/math-comp#245]
I'd like to see the [math-comp](https://github.com/math-comp) libraries covered by CI for `math-comp/math-comp`, just to be sure no change in this fundamental part breaks e.g. `odd-order`, `analysis`, `finmap` and other libraries.

This issue is related to #159.

**Comment by CohenCyril** [comment]
Also related to #243

**Comment by anton-trunov** [comment]
I could try to help with this. If anyone had any pointers as to where begin, it would be very much appreciated. (CC @ejgallego)

**Comment by ejgallego** [comment]
Fortunately we have advanced a bit here, so there are 3 options:
- Use gitlab's CI + `coqbot`. This is the solution we use in Coq, and we are quite happy to it, but it is a bit more inconvenient as you have to setup a bot.
- Use docker: thanks to the work of @erikmd , there are excellent Docker images availabe; so the idea is that you would start from a Coq's Docker image, then push another one with a built math-comp, then test the rest of CI.
- Use Nix: this is the work of @Zimmi48 and does indeed allow pretty quick testing thanks to the binary cache.

I guess whoever gets to do this first will choose the solution; anyways I think the current travis setup should switch to docker or nix regardless of what happens, no point on building Coq.

**Comment by Zimmi48** [comment]
>but it is a bit more inconvenient as you have to setup a bot.

If this path is chosen, I can help setup the synchronization.

>Use Nix: this is the work of @Zimmi48 and does indeed allow pretty quick testing thanks to the binary cache.

Unfortunately, I have not yet reached the point where the binary cache can be used for Coq packages. There is nothing really blocking. I just need to set things right. I will try to get back to this soon.

**Comment by Zimmi48** [comment]
See more info on the Cachix question here: https://github.com/coq-community/manifesto/issues/37

**Comment by erikmd** [comment]
This issue was addressed by PR #272 that consisted in adding:

* https://github.com/math-comp/odd-order with coq-8.7
* https://github.com/math-comp/fourcolor with coq-{8.6, 8.7, 8.8, dev}
* https://github.com/coq-community/lemma-overloading with coq-{8.8, 8.9, dev}

BTW @anton-trunov had proposed [to add two other libraries in math-comp's CI (in #256)](https://github.com/math-comp/math-comp/pull/256#issue-235958635):

* https://github.com/imdea-software/fcsl-pcm
* https://github.com/math-comp/analysis

(but IINM these two upstream repos don't have a working CI configuration for the moment)

Actually, I propose to keep this issue #245 open for a while so the math-comp devs can comment on whether they'd like to see other libraries added in the CI as well(?)

Kind regards, Erik

**Comment by CohenCyril** [comment]
@erikmd
- https://github.com/math-comp/analysis had a working CI until the switch to opam 2 :cry:
- I would like to add https://github.com/math-comp/finmap (although I am not sure how to handle the fact it is currently slowly big merged in math-comp), https://github.com/math-comp/bigenough and 
https://github.com/math-comp/real-closed to the CI

**Comment by ejgallego** [comment]
Is odd order tested?

**Comment by erikmd** [comment]
@CohenCyril 
> I would like to add https://github.com/math-comp/finmap (although I am not sure how to handle the fact it is currently slowly big merged in math-comp),

maybe I'm missing something here, but it seems to me that adding finamp to math-comp CI now should not cause some issue, as you could change the `.gitlab-ci.yml` again in the same PR than the PR to integrate finmap(?)

@ejgallego 
> Is odd order tested?

Yes, but only for Coq 8.7 (see e.g. [this pipeline](https://gitlab.com/math-comp/math-comp/pipelines/46229431)), because this was the Coq version chosen in the upstream repo; but you might want to also test other versions of Coq(?)

**Comment by ejgallego** [comment]
Oh, I see; thanks @erikmd , I missed it. IMHO it would interesting to test everything with `coq-dev`

**Comment by CohenCyril** [comment]
> maybe I'm missing something here, but it seems to me that adding finamp to math-comp CI now should not cause some issue, as you could change the `.gitlab-ci.yml` again in the same PR than the PR to integrate finmap(?)

yes you are right

**Comment by pi8027** [comment]
I will reimplement interval.v on top of order.v in the coming months. So I need real-closed in the CI too.

**Comment by erikmd** [comment]
@pi8027 thanks for the suggestion, I plan to prepare a new PR accordingly (taking into account @ejgallego's [suggestion](https://github.com/math-comp/math-comp/pull/294#issuecomment-469649603)) as soon as possible, ideally before the end of the week.
