### ISSUE TITLE
view negPf

### ISSUE THREAD

**Issue by thery** [math-comp/math-comp#284]
Hi,

Views usually work in both direction

Goal forall a b : bool,  a /\ b.
move=> a b.
apply/andP. (* a && b *)
apply/andP. (* a /\ b *)

Why this is not the case for negPf ?

Goal forall a : bool,  ~~ a.
move=> a.
apply/negPf. (* a = false *)
apply/negPf. (* a = false *)

**Comment by ggonthier** [comment]
`negPf` is a little special because it is a `reflect` view whose `Prop` argument is a `bool` equality. In general `reflect` views can be applied in either direction (`bool -> Prop` or `Prop -> bool`). The `apply/` view hints give priority to the `Prop -> bool` direction, because this direction requires a more specific pattern: a boolean equality whose left hand side matches the `bool` argument of the `reflect` view, allowing for either removing or inserting a negation. If the reverse priority were used then `apply/eqP` would never work on `bool` goals, e.g., turning `n == 1` to `(n == 1) == true`!
   Here `a = false` happens to match the `bool` pattern, with the head `negb` removed, and the `introTFn` hint is used, changing the goal to `if false then a <> false else a = false`, which is immediately reduced back to `a = false`; `Show Proof` will give you the whose story.
   To get back to `~~ a` in this situation, you need to use either `apply/negbTE` or `apply/idPn`. I do realise this can be confusing; to remove this ambiguity we'd have to state `negPf` using `<->` rather than `reflect`, which would break the fairly common `rewrite (negPf not_a)` idiom.

**Comment by thery** [comment]
I am not sure to understand, is it because we want views on booleans to work not only when we have 
a goal that is `is_true b_exp`  but also when it is `b_exp = false` ?

**Comment by ggonthier** [comment]
Yes, @thery, precisely; as well as `~~ b_exp = c`, and `b'_exp = c` when `b_exp` is `~~ b'_exp`. So there are six `reflect` hints for `move/` and `apply/` each (see `ssrbool.v`).
