### ISSUE TITLE
Clean, refactor and document the regression test for the structure hierarchy

### ISSUE THREAD

**Issue by amahboubi** [math-comp/math-comp#308]
Since the library is compiling before the merge, such a test would materialize the change operated by #291.

**Comment by gares** [comment]
This requires putting back some support for a test suite.

**Comment by CohenCyril** [comment]
@gares and @amahboubi could we postpone that to the next milestone?

**Comment by gares** [comment]
I can take care of this, or at least the infrastructure part. I still need a file that triggers the inference.

**Comment by pi8027** [comment]
I will provide a small .v file for this.

**Comment by pi8027** [comment]
This is a test for the join structure of `countRingType` and `finZmodType`, successful on #291, and failed on the master.
```coq
Require Import all_ssreflect all_algebra.
Check erefl : ((_ : countRingType) : Type) = ((_ : finZmodType) : Type).
```

We need to see the output to check which structure is obtained:
```coq
erefl (?t : countRingType)
  : ((?t : countRingType) : Type) =
    ((FinRing.Ring.countRing_finZmodType ?t : finZmodType) : Type)
     : ?t = FinRing.Ring.countRing_finZmodType ?t
where
?t : [ |- finRingType]
```

**Comment by gares** [comment]
Yes!

**Comment by CohenCyril** [comment]
Thanks @pi8027, I turned it into a tool and pushed it in #291 to identify missing joins.

**Comment by pi8027** [comment]
@CohenCyril Thank you for the nice tool!

I found a better way to check which structure is obtained by unification, but test case generation would be more difficult:
```
Ltac check_join T1 T2 Tjoin :=
  let t1 := open_constr:(_ : T1) in
  let t2 := open_constr:(_ : T2) in
  unify (t1 : Type) (t2 : Type);
  match t1 with
    | _ ?tjoin => match type of tjoin with Tjoin => idtac end
  end.

Goal False.
check_join countRingType finZmodType finRingType.
check_join finZmodType countRingType finRingType.
Fail check_join finZmodType countRingType finUnitRingType.
Abort.
```

**Comment by CohenCyril** [comment]
@pi8027 I openned PR #318 to try your test script, but I did not take the time to implement a correct topological sort. If you have some time to hack on it, please be my guest.

**Comment by pi8027** [comment]
@CohenCyril I will do it. I guess that what we need is not a topological sort.

**Comment by pi8027** [comment]
I have finished the complete test cases generation and found some bugs. I will prepare a PR.

**Comment by pi8027** [comment]
Automated test cases generation for the hierarchy is available. So one may close this issue. But there are some minor issues:
1. Now we have two tools on hierarchy stuff: `hierarchy-diagram` and `hierarchy_test.py`. Unifying them as one tool might be better because the latter one uses the output of the former one.
2. The generated test cases file (`hierarchy_test.v`) is now a part of the `math-comp` repository. I prefer to remove this file and to make the whole the test process is done by `make test-suite`.
3. There is no documentation for `hierarchy_test.py`.

The choice of the implementation language of the tools is important to make the test suite accessible to everyone. I prefer to reimplement them in OCaml, but this may require a regexp library (I don't know which one is the best) or Menhir.

**Comment by CohenCyril** [comment]
Let us keep this issue open and rename it though
