### ISSUE TITLE
Issue with the Howto release

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/math-comp#327]
Missing steps for [Howto Release](https://github.com/math-comp/math-comp/wiki/Howto-Release):
- [x] how to publish released docker images
- [x] how to update the online documentation

cc @gares 
cc @erikmd

**Comment by gares** [comment]
I think that to update the doc one has to build and the commit what is in doc/ (there was a Makefile there)

**Comment by erikmd** [comment]
Hi @CohenCyril @gares,

> how to publish released docker images

is now documented in [this section of the wiki](https://github.com/math-comp/math-comp/wiki/Howto-Release#docker-images) (feel free to comment if you have questions or remarks)
− I put that section after the section about `opam` because the Docker images precisely depend on opam

I guess you could tick the first box in [the original post](https://github.com/math-comp/math-comp/issues/327#issue-430898578) (I don't have the rights to do so)

IINM the second checkbox amounts to https://github.com/math-comp/math-comp/issues/349 (I'm still willing to look into this, in a couple of days)

Kind regards, Erik

**Comment by affeldt-aist** [comment]
Note that how to generate the doc is documented [here](https://github.com/math-comp/math-comp/wiki/Howto-Release#before-you-start-the-actual-process-lets-say-in-the-morning-before-lunch).

**Comment by affeldt-aist** [comment]
Our (@affeldt-aist , @ybertot ) experience with the release of 1.11.0+beta1 is that the now semi-automated generation of the doc and of the docker images still needs to be tested by more people.

**Comment by gares** [comment]
My understanding is that some files should be (also) committed in the main repo, so that the make doc target can prepare a complete "website". In this way replacing the old website with the new one should be a no brainer.

**Comment by CohenCyril** [comment]
@ybertot @affeldt-aist AFAIU this is now fixed, right?

**Comment by ybertot** [comment]
I agree that this could be closed.  The Howto relase document is now much more informative.
