### ISSUE TITLE
Compatibility 1.9.0

### ISSUE THREAD

**Issue by thery** [math-comp/math-comp#362]
When trying to update 

https://github.com/math-comp/tutorial_material

from ``1.7.0`` to ``1.9.0``.

The following proof breaks 
````
Lemma plus_commute : forall n1 m1, n1 + m1 = m1 + n1.
Proof.
by elim=> [| n IHn m]; [elim | rewrite -[n.+1 + m]/(n + m).+1 IHn; elim: m].
Qed.
````
It seems that the problem comes from the fact that the theorems ``plus_n_O`` and ``plus_n_Sm`` are not applied automatically anymore.

**Comment by ggonthier** [comment]
This was a deliberate decision to remove the accidental dependency of MathComp on pervasive lemmas, which was an accidental consequence of more aggressive unification in `Trivial` - see #344.

**Comment by thery** [comment]
mea culpa it was in the change log

**Comment by thery** [comment]
@ggonthier I understand the
````
Remove Hints plus_n_O plus_n_Sm mult_n_O mult_n_Sm : core.
````
for dependancy but we  could have added
````
Hints Resolve addn0 addnS muln0 mulnS : core.
````
to preserve compatibility.

**Comment by ggonthier** [comment]
The point of the PR was that these hints were undesirable. MathComp is selective about the hints it puts in the core base, limiting itself to immediate reflexivity properties (`leqnn`, `eqxx`) and  typing properties (`group1`, `index_gt0`) that occur frequently. The reason is that hint application can be unreliable in the presence of unification hints, leading to fragile proof scripts. Indeed, `group1` used to have to be declared with multiple variants to be at all useful; we've since started to improve on this by using `Hint Extern` (in #337).
   Lemmas `addn0`, ... do not meet this criteria, and are not very useful, as the modest scope of #344 shows, so they would not be declared as hints (and had not been). Their Coq counterparts used to be ignored due to the use of aliases of arithmetic operators in `ssrnat`, but became active at some point when `trivial` started using more aggressive unification, and some scripts ended up using them by accident or by blind minimisation. In fact they are most likely to get used in tutorial material that rehashes basic arithmetic, and I feel this is harmful, since it give the impression that scripts succeed unprediactably by pulling obscure random hints out of thin air.
  The conclusion is that adding `addn0`,... as hints would merely have perpetuated the issue rather than fixing it - so we didn't do it. If you want to write scripts that use a lot of hint automation, of a tutorial on doing so, then you can declare your own selection - but this isn't the default style for MathComp.

**Comment by thery** [comment]
Yep it broke a couple of proofs in the tutorial material :
https://github.com/math-comp/tutorial_material/commit/7b8938c1d1a16e126fd4f4bb992982976bf1445b

**Comment by ggonthier** [comment]
My point, precisely: that tutorial material promotes a proof style (hope some random core hint finishes off a proof for you) that is not relevant for most of the library, rather than showing how one would usually complete proofs using basic algebraic lemmas. The "fix", by the way, is improper: the proof scripts should invoke explicitly the relevant lemmas, rather than fiddling with the hint database.

**Comment by thery** [comment]
@ggonthier 
As
https://hal.archives-ouvertes.fr/inria-00407778/
 explains the tactic step by step, I think it is better to keep it in sync with what is written.

**Comment by soraros** [comment]
It would be better if we could update the tutorial itself. It was exactly `plus_commute` that motivated me to do #344: in the proof term it's `by` that does all the work by picking up `addn0` and `addnS`. That was very confusing for a novice like myself.
I really hope the script can be fixed(since now `elim` does nothing, I consider the proof script incorrect). And if the tutorial ever get updated, maybe it's good time to fix some other things too. For example to use `Variant` instead of `Coinductive`. But that's off topic of course.

**Comment by thery** [comment]
Ok I've updated the code so it does not use

https://github.com/math-comp/tutorial_material/blob/45dca26c5f945b64e7f876c0861d23cc3caa66cc/AnSsreflectTutorial/tutorial_Gonthier_LeRoux.v#L252-L258

I agree with @soraros, if @ggonthier still has the latex code somewhere it would be nice to put on hal an updated version of the [technical report](https://hal.archives-ouvertes.fr/inria-00407778/). But this is another issue, so I close this one
