### ISSUE TITLE
"set" with parentheses calls Coq's set tactic

### ISSUE THREAD

**Issue by maximedenes** [math-comp/math-comp#37]
I wan't aware until today that writing "set (x := t)" in ssreflect (as opposed to "set x := t") seems to actually call Coq's set, whose matching has all sorts of bad behaviors like https://coq.inria.fr/bugs/show_bug.cgi?id=4636

I find this way of switching between ssr's tactic and Coq's equivalent very fragile, compared to the usual ":" (or "<-" / "->" for rewrite). It could be especially confusing for people transitioning from plain Coq to ssr.

**Comment by ggonthier** [comment]
These tactics are well documented, and I don’t see that the syntax distinction is fragile, since the grammars are LL-unambiguous. The worst that could happen would be that the ssreflect set/pose would supersede the native Ltac tactics if Coq decided to drop the surrounding brackets. This seems unlikely as it would reverse the decision not to allow lconstr arguments at the end of tactics, in particular to avoid conflict with the Ltac ‘||’ and ‘;’ combinators (math-comp uses do [..|..] for the former, and does not overload ‘;’ in Gallina).
    We could implement an option to flag or disallow the Ltac syntax when the ssreflect syntax is active, though that seems going out of our way to decrease Ltac compatibility. Did you have that in mind?
