### ISSUE TITLE
backport ssrbool to Coq

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/math-comp#526]
Backport to Coq new contents from `ssrbool.v` (as introduced by PR #513 PR #519 PR #499 ).

https://github.com/affeldt-aist/coq/tree/ssrbool_backport_MathComp1.11
already contains an `ssrbool.v` file with an integration of PR #513, PR #519, and PR #499 
and is ready to be PRed.

@CohenCyril @ybertot 

(NB: this issue has been edited, it was mentioning `ssrfun.v` but its contents have already made their way to Coq)

**Comment by chdoc** [comment]
Note that PR #499, which is hopefully going to be merged soon, also includes additions to `ssrbool.v`. So you may want to hold off on this for a few more days.

**Comment by chdoc** [comment]
PR #499 has been merged.

**Comment by affeldt-aist** [comment]
> PR #499 has been merged.

Thank you for letting me know. I have updated the tentative backport accordingly.

**Comment by chdoc** [comment]
Maybe the `contra` lemmas should be integrated with the other `contra` lemmas already present in that file, i.e., somewhere around [this line](https://github.com/coq/coq/blob/ba355fb8eb41cd25cf7bd1ece860c93d32e5793c/theories/ssr/ssrbool.v#L548). Possibly the whole set of lemmas could be wrapped in a section with the appropriate `Implicit Types ...` command.

**Comment by pi8027** [comment]
I hope this will be done before the feature freeze of Coq 8.13, which is 15 Nov. (see coq/coq#12334)

**Comment by CohenCyril** [comment]
Wasn't this fixed in https://github.com/coq/coq/pull/12898?

**Comment by pi8027** [comment]
I was not aware of that, but it does not seem to include #552.

**Comment by chdoc** [comment]
Yes, the problem was/is that recent versions of `ssr.ssrbool.v` declare a reserved notation for `[rel _ _ : _ | _]` (rel with explicit typing) with a particular printing format. Prior to the fix, mathcomp was redeclaring this notation in ssreflect.ssrbool.v. However, one needs to give level information to please old versions of Coq that don't yet provide the reserved notation. This invalidates the preexisting format. Moreover, one cannot provide an equivalent format string at this point, because `only parsing` notations don't take format strings. Thus, mathcomp needs to repeat the `Reserved Notation` command for the time being, as this is the only way to declare `only parsing` notations with a particular format :grin:

**Comment by pi8027** [comment]
I see. So shall we close here?

**Comment by affeldt-aist** [comment]
I think we can close. I forgot to do so when the backport was merged (https://github.com/coq/coq/commit/40140bfc872b104d184ba05a85f6ce918559a6ba, https://github.com/coq/coq/commit/bfd384ed5f7af818f6b893b50d0f8de49477c144, https://github.com/coq/coq/commit/3405ab8405e141dd0a28c72c8ca221ed6f50dfed).
