### ISSUE TITLE
feature: notation for lists conforming to the general schema

### ISSUE THREAD

**Issue by gares** [math-comp/math-comp#54]
This code seems to work here:
```
Notation "[ :: x1 , x2 , .. , xn : s ]" := (x1 :: x2 :: .. (xn :: s) ..)
  (at level 0, format
  "'[hv' [ :: '['  x1 , '/'  x2 , '/'  .. , '/'  xn ']' '/ '  :  s ] ']'").

Check fun l => [:: true, false , false : l].
```

The general schema seems to be
```
[operator item, item, ..., item short_operator item]
```
For seq the short operator is & and I quite don't get why (and I have hard times explaining it).

@ggonthier is there a reason behind the current choice?

**Comment by gares** [comment]
Another alternative could be to always use & as the terminator I guess.  It would still look more consistent to me.

**Comment by ggonthier** [comment]
The design is that `&` is the default terminal separator, but other separators can be used when appropriate, so that the notation "reads" better, e.g., `[\/ A, B | C]` as "A, B _or_ C".
   It is important that the terminal separator be symbol that is a _separator_ in the Coq grammar, i.e., that it cannot be construed as an infix operator. Nominally, all sequence items are parsed at level 200 (least binding), so `false : l` should be parsed as a type cast in your example. So either it is, and you've been saved by some odd error recovery of the stream parser, or you're overriding the cast syntax in manifest sequences, and something like `[:: a && b : nat; true]` will no longer parse.

**Comment by gares** [comment]
I agree on the aesthetic point, and you gave me a way to explain all this.
