### ISSUE TITLE
stale docker image `mathcomp/mathcomp-dev:coq-dev`

### ISSUE THREAD

**Issue by chdoc** [math-comp/math-comp#681]
I just noticed that the `mathcomp/mathcomp-dev:coq-dev` docker image hasn't been rebuilt for 7 days:
```
coq-dev
Last pushed7 days ago
```
This actually now causes build-failures for `coq-elpi` (see: https://github.com/LPCIC/coq-elpi/issues/200)

(https://hub.docker.com/r/mathcomp/mathcomp-dev points here, so I hope this is the right place to file this.)

CC: @erikmd

**Comment by erikmd** [comment]
Hi @chdoc, thanks for opening this issue!
i re-enabled the scheduled pipeline https://gitlab.com/math-comp/math-comp/-/pipeline_schedules so that `mathcomp/mathcomp-dev:coq-dev` is rebuilt at least once a day (it should have not been disabled in the first place, sorry for that)
Example pipeline: https://gitlab.com/math-comp/math-comp/-/pipelines/225437072

Finally as I mentioned in Zulip just now, the plan is replace this scheduled pipeline with an automatic, immediate trigger, like what is currently done for `coqorg/coq:dev` and `coqorg/coq:8.13-alpha` from `coq@master` and `coq@v8.13`;
[docker-keeper](https://gitlab.com/erikmd/docker-keeper) has been extended to this aim (this morning :), but a second extension is still needed for mathcomp… so I let you know ASAP and close this issue when it is done.
