### ISSUE TITLE
`apply: divr_gt0` for `0 < _ :> rat` can be slow to fail

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#698]
```coq
Goal forall x y : rat, 0 < x - y.
Proof.
move=> x y.
Time Fail apply: divr_gt0.
(* Finished transaction in 14.916 secs (14.907u,0.s) (successful) *)
Abort.
```

The following behavior is also interesting. IIUC, it finds the fact that both `1` and `_ / _` of type `rat` can be reduced to `fracq (_, _)` and then unifies their arguments respectively.
```coq
Goal 0 < 1 :> rat.
Proof.
apply: divr_gt0 => /=.
(*
  ============================
  0 < numq 1

subgoal 2 (ID 22458) is:
 0 < 1 %/ gcdn 0 1
*)
```

**Comment by CohenCyril** [comment]
Well spotted! I am not sure how to deal with that, since we still want operations to compute, we cannot lock, but if we do not lock we can get heavy slowdowns as you uncovered. Maybe a hybrid mode where ssr `/=` would perform a delimited unlocking (i.e. unlocking tagged as "safe") but that would also prevent some conversions at type level :-/.
Maybe we should find another way to proceed, hacking into Coq unification (adding these "modes")

**Comment by ggonthier** [comment]
A likely solution would be to interlock the definition of ``fracq``, so that it does not return a constructed expression (a ``Rat _ _``) unless _both_ its arguments are constructors. This way, computation can proceed for ground instances, but comparison will not dive into the definition of ``fracq`` in abstract instances, and instead focus directly on its ``int`` arguments (to speed things up, the actual details of the computation could be hidden by an auxiliary definition).
   If this does not suffice, you can try deeper matches on the ``fracq`` arguments (e.g., match specifically ``Zpos 0``), interlocking the definitions of ``addq``, ``mulq``, etc., so they do not compute unless their arguments are ``Rat`` constructors, and, as a last resort, using _different_ specializations of ``fracq`` for each arithmetic operation.

**Comment by CohenCyril** [comment]
By interlocking, do you mean writing e.g. `addq x y := match x, y with Rat _ _, Rat _ _ => [...]` even if we then reuse `x` and `y` in their non expanded forms, but so that reduction will be stuck unless both `x` and `y` are ground?

**Comment by CohenCyril** [comment]
And the same for `fracq` matching either on an explicit pair, and possibly on the constructors of `int`?

**Comment by ggonthier** [comment]
1) It is somewhat better to use the arguments of ``Rat`` in the "locked" definition, as in
```addq '(Rat _ xP) '(Rat _ yP) (x := Rat _ xP) (y := Rat _ yP) := ...```
so that if the arguments happen to match (e.g., matching  ``x + y`` against ``_ * _``), then the bodies are ground terms that do not depend on ``x`` and ``y``
2) ``fracq`` is always called on an explicit tuple, so it is necessary to match on the ``int`` constructors to achieve interlocking. If ``fracq`` is also called with explicit ``Zpos`` arguments, then further matching on ``0``, as I suggested, would be preferable.

**Comment by CohenCyril** [comment]
I did some quick experiments, it is not sufficient to interlock `fracq` (even down to `Posz 0`) but adding the interlocking of operations on top if that is enough. Thanks!!
