### ISSUE TITLE
Attend warning `deprecated-hint-rewrite-without-locality`

### ISSUE THREAD

**Issue by proux01** [math-comp/math-comp#892]
```
Warning: The default value for rewriting hint locality is currently "local" in a section and "global"
otherwise, but is scheduled to change in a future release. For the time being, adding rewriting hints outside
of sections without specifying an explicit locality attribute is therefore deprecated. It is recommended to use
"export" whenever possible. Use the attributes #[local], #[global] and #[export] depending on your choice. For
example: "#[export] Hint Rewrite foo : bar." [deprecated-hint-rewrite-without-locality,deprecated]
```
Will be fixed by adding the `#[global]` attribute to the `Hint Rewrite` in fingroup.v but this requires Coq 8.14 (so we should fix this when dropping Coq 8.13).

**Comment by MSoegtropIMC** [comment]
A note: this currently gives an issue in Coq Platform's Smoke test kit, which happens to test file fingroup.v. I am currently patching this file when copying it to the smoke test.

**Comment by proux01** [comment]
Alternatively, we can change the smoke test (for instance `mathcomp/ssreflect/bigop.v`), fingroup happens to contain the only `Hint Rewrite` in the library.

**Comment by MSoegtropIMC** [comment]
I have one smoke test file per opam package, so I would need a file from fingroup. Possibly a dedicated example file in fingroup would be helpful.

**Comment by proux01** [comment]
Then `mathcomp/fingroup/morphism.v` could do the job for instance.

**Comment by MSoegtropIMC** [comment]
It also has one Hint without locality attribute in it: https://github.com/math-comp/math-comp/blob/07f0b63cd3ea1e7a5ad79282b015f70b427ee69a/mathcomp/fingroup/morphism.v#L1493

**Comment by proux01** [comment]
Indeed, let's go for `mathcomp/fingroup/quotient.v` which doen't have any `Hint` and should be more robust with respect to those changes.

**Comment by MSoegtropIMC** [comment]
Thanks, I put it on my pre-release check list to exchange the file.

Still I think it might make sense to have a few example files in the mathcomp repo. Sure there is the excellent mathcomp book and mathcomp files generally have useful documentation, but different people have different approaches. There are now so many Coq developments that people have to choose between different options, and to get a quick overview to judge if it makes sense to dig deeper into a development, an example file would be useful. IMHO the mathcomp documentation picks up people at the point where they already decided to use it. Mathcomp is so big so that to a certain extent this is justified (in the sense that there is simply no way around it) but still it would not hurt to have example files.

**Comment by proux01** [comment]
Thanks for the comment, we'll discuss that at our next meeting.

**Comment by MSoegtropIMC** [comment]
I just wanted to note that I now replaced the Coq Platform smoke test kit file as suggested above by @proux01 (CI results for all older versions of Coq Platform still open - I only tested the most recent ones).
