### ISSUE TITLE
Export to Ltac matching result

### ISSUE THREAD

**Issue by gares** [math-comp/math-comp#96]
The matching machinery can export to ltac the instance of the pattern.
This helps the implementation of third party code using ssrmatching.
Needed by @erikmd

**Comment by erikmd** [comment]
Hi @gares,
Thanks for opening this issue!
So let me precise the features of the tactic I would need to simplify my implementation of the under tactic (cf. https://github.com/erikmd/ssr-under-tac) and even to extend it, see below (§).

I would need a tactic that is similar to "ssrpattern [pat]" and "rewrite [pat]lemma", but has the following features:
* it selects the occurrences of pat that matches the lhs of lemma
* it rewrites lemma on these occurrences **and it instantiates as much evars as possible** (a bit like plain Coq's "rewrite -> lemma")
* finally **it exports the rhs of the instantiated lemma** (e.g. by adding it on top of the goal stack).

I don't know what would be the best naming for this tactic, maybe "rewrite1 [pat]lemma" ?

* while we are on it, this wished tactic **rewrite1 could also accept occurrence patterns**  
  such as "rewrite1 {occ}[pat]lemma" :)

(§) The availability of such a tactic would lead to a more expressive "under" tactic: namely currently we can write something like
```
under [X in _ = X + _] eq_bigr [i Hi] rewrite GRing.mulrDl.
(* or *)
under [LHS] eq_bigr [i Hi] rewrite lemma.
```
but the following cannot be achieved currently, given the matching with pat and the consideration of lemma are done sequentially, and that "ssrpattern [in RHS]" does not work in the first place:
```
under [in RHS] eq_bigr [i Hi] rewrite lemma.
```
Do you think you could implement a tactic "rewrite1 {occ}[pat]lemma" that behaves as described above?
With kind regards, Erik

**Comment by gares** [comment]
Which semantic difference do you see between `under [LHS]` and `under [in LHS]`?

Could you clarify bullet 2 (instantiate evars).  Why are there evars there?

**Comment by erikmd** [comment]
Hi @gares,
> Which semantic difference do you see between under [LHS] and under [in LHS]?

the difference is that the [LHS] pattern is unambiguous, while the [in LHS] pattern does not say precisely which term should be selected. As a result, it is possible to write "ssrpattern [LHS]", unlike "ssrpattern [in LHS]". Hence the current limitation of the under tactic I was mentioning  my implementation of the under tactic.

> Could you clarify bullet 2 (instantiate evars). Why are there evars there?

**Comment by erikmd** [comment]
Hi @gares,
> Which semantic difference do you see between under [LHS] and under [in LHS]?

the difference is that the [LHS] pattern is unambiguous, while the [in LHS] pattern does not say precisely which term should be selected. As a result, it is possible to write "ssrpattern [LHS]", unlike "ssrpattern [in LHS]". Hence the limitation I was talking about in the current implementation of the under tactic.

> Could you clarify bullet 2 (instantiate evars). Why are there evars there?

In my implementation, there are two kinds of evars:
* the evars that I append to the user-specified lemma to overcome the fact that Ltac does not handle implicit arguments (let us say that the term so obtained is the "padded lemma")
  cf. https://github.com/erikmd/ssr-under-tac/blob/53cb2072f6ca5ee32f87a85ea518ccfbabee7f34/src/under.v#L30
* the 3 evars that I create in the end to instantiate the padded lemma with the function to-be-refined
  cf. https://github.com/erikmd/ssr-under-tac/blob/53cb2072f6ca5ee32f87a85ea518ccfbabee7f34/src/under.v#L109

I had performed several tests and it happens that if no evar is instantiated during the rewrite, it is very difficult for the user to instantiate them afterwards... Hence my suggestion of implementing a "rewrite1" tactic.

Cheers, Erik

**Comment by erikmd** [comment]
Hi @gares,
Cc @CohenCyril
I'm still very interested in contributing some `under` tactic for math-comp 1.7 (cf. #97 and [this repo](https://github.com/erikmd/ssr-under-tac)), which depends on this issue.
To sum up, this requested "`rewrite1 {occ}[pat]lemma`" tactic would be very handy to (re)implement my `under` tactic in a much more concise way (avoiding too much Ltac hacking) so I could then propose a PR towards the math-comp repo.
I realize that Coq 8.7.0 is now available with ssrmatching and ssreflect, so comes the question whether this `under` tactic should be proposed instead to be integrated in Coq... It seems to me that on the one hand, the `under` tactic is quite general, but on the other hand it would mostly be useful to leverage the extensionality lemmas such as those of `bigop`, `finfun`, `finset`, `matrix`, which are part of math-comp, so maybe it would seem natural to integrate these two tactics "rewrite1" and "under" in math-comp... which would also make it available for more users (not only Coq 8.7 but also Coq 8.6 users for example). Do you agree?
Side question: what are your plans regarding the Coq version compatibility and the contemplated date of the upcoming release of math-comp? (I'm asking that because some related issues impact Coq 8.4 or 8.5 for example, cf. #61 and #62).
I'll have very few time upto the next week-end but I'm ready to test code or discuss more on this next week or the following if need be.
Kind regards

**Comment by herbelin** [comment]
Hi, please excuse my ignorance in advance as my question may miss the point: would it make sense that `rewrite` itself provides the `under` feature?

**Comment by erikmd** [comment]
Hi @herbelin, thanks for your comment! Actually I don't think the `rewrite` itself could subsume `under`:
`under` is a tactic notation that uses a ssrpat. and a specific extensionality lemma such as eq_bigr or eq_bigl, to apply any tactic (for example a single tactic such as rewrite, but more generally any "tactic3" Ltac) on a goal generated on-the-fly with evars:
`under [ssrpattern] eq_lemma [intropattern] tactic3.`
Thus it amounts virtually to manipulate the general term "under the bigop" (or a similar operator).
Also it is compositional, so we can write
`under eq_bigr k under eq_bigl l rewrite setIT.`
The issue here is that the current implementation of `under` uses the `ssrpattern` tactic from `ssrmatching`, which allows writing
`under [LHS] eq_bigr [i Hi] rewrite lemma.`
but prevents doing
`under {2}[in LHS] eq_bigr [i Hi] rewrite lemma` for example.
So if I could rely on a `rewrite1` tactic as requested in this issue, this would improves that, and shorten the code of the `under` tactic itself.

**Comment by herbelin** [comment]
Maybe my naive question is: couldn't the use of the appropriate extensionality lemma be found automatically whenever "possible" by the call to `rewrite`. At least, this seems possible in the case of bigops combinators. (I say naive because I did not effectively run your tactic, so I'm only roughly guessing what it does mentally.)

**Comment by erikmd** [comment]
I don't think we could automatically infer the extensionality lemma from the term at stake because in practice the applicable lemma is not unique (e.g. in general, both `eq_bigl` and `eq_bigr` are applicable) and also I'd expect the extensionality lemma helps selecting the term to be changed, not the other way around...

**Comment by herbelin** [comment]
OK, I believe I see. The name of the lemma contributes to tell in which subterm we want to rewrite.

But then, couldn't the information telling if one wants to reduce in the operand or in the range (don't know how you call the "l" and "r" part) be part of the pattern given to `rewrite`? Maybe using keywords such as `OPER` or `RNG`, in the spirit of `LHS` and `RHS`? Or do I miss something?

**Comment by herbelin** [comment]
To be clear, I find the idea of `under` very good. My question is actually not about `under`, but about whether `rewrite` could eventually include the feature that `under` provides.

**Comment by gares** [comment]
It is related to setoid rewriting indeed, but the context under which you rewrite is typically "weaker" than the one of setoids: it is made of morphisms that give you and extra property (eg that the variable is in the range of the iterated op).

**Comment by CohenCyril** [comment]
@gares @erikmd what is the status of this issue? Transferred to Coq? Solved?

**Comment by erikmd** [comment]
@CohenCyril yes, exactly: it is addressed by the implementation of the `under` tactic in PR coq/coq#9651, so I guess you can close #96 and mark it as transferred to coq (the `under` feature will be available using `From Coq Require Import ssreflect`)
