### ISSUE TITLE
Names `mulrzDl` and `mulrzDr` have to be exchanged?

### ISSUE THREAD

**Issue by pi8027** [math-comp/math-comp#997]
```coq
From mathcomp Require Import all_ssreflect all_algebra.

Check (mulrzDl _ _ _).
Check (mulrzDr _ _ _).
```

```
mulrzDl ?x ?x0 ?y
     : (?x *~ (?x0 + ?y))%R = (?x *~ ?x0 + ?x *~ ?y)%R
mulrzDr ?m ?x ?y
     : ((?x + ?y) *~ ?m)%R = (?x *~ ?m + ?y *~ ?m)%R
```

It looks to me that `mulrzDl` and `mulrzDr` are right and left distributivity lemmas respectively. I think they should be eventually renamed to `mulrzDr` and `mulrzDl` respectively.

**Comment by proux01** [comment]
I agree those are reverted and should be fixed. I guess the best solution is to deprecate them asking to use `mulrzDr_tmp` and `mulrzDl_tmp` instead and two versions later fix them and deprecate the `*_temp` so things would get fixed in 4 versions and users can still easily support two consecutive versions.
